In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df  = pd.read_csv('student_marks.csv')
df

study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]

In [ ]:
plt.scatter(df.study_hours, df.student_marks)
plt.xlabel("Students Study Hours")
plt.ylabel("Students marks")
plt.title("Scatter Plot of Students Study Hours vs Students marks")

In [3]:
df.isnull().sum()

study_hours      5
student_marks    0
dtype: int64

In [4]:
df = df.fillna(df.study_hours.mean())

In [5]:
df.isnull().sum()

study_hours      0
student_marks    0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['study_hours']],df[['student_marks']], test_size = 0.2) 

In [7]:
X_train

study_hours
0       6.830000
198     6.600000
18      8.410000
136     8.160000
31      6.995949
..           ...
23      5.850000
178     8.420000
122     6.995949
96      6.995949
116     5.400000

[160 rows x 1 columns]

In [8]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [9]:
model.score(X_test, y_test)

0.954487491235019

In [10]:
model.coef_

array([[3.91754056]])

In [11]:
model.intercept_

array([50.53520418])

In [12]:
model.predict([[8]])

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[81.87552867]])

# Save Model To a File Using Python Pickle

In [13]:
import pickle

In [14]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

# Save Model To a File Using Python Joblib

In [15]:
import joblib as jbl

jbl.dump(model,'My_JobModel')

['My_JobModel']